import type { Metadata } from "next";
import { initializeApp } from "firebase/app";

import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ weight: "500", subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const firebaseConfig = {
  apiKey: "AIzaSyBvkL3EXBGrRts49Ur2ZCmOB40vaB1na00",
  authDomain: "ignite-450e9.firebaseapp.com",
  projectId: "ignite-450e9",
  storageBucket: "ignite-450e9.appspot.com",
  messagingSenderId: "305327530230",
  appId: "1:305327530230:web:2e5b34815846d53b260cd7",
  measurementId: "G-8N39R1CGZ8",
};

export const app = initializeApp(firebaseConfig);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
